---
#- name: set hostname
#  shell: hostnamectl set-hostname "{{server.yourdomain.com}}"
#  tags: [set_hostname]

- name: Add epel-repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  tags: [enable_epel]

- name: install yum-utils
  yum:
    name: yum-utils
    state: present
  tags: [install_utils]
- name: diable php54 and enable php73
  shell: yum-config-manager --disable remi-php54 && yum-config-manager --enable remi-php73
  tags: [enable_php73]

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
    state: present
  tags: mariadb

- name: update packages
  yum:
      name: "*"
      state: present
  tags: [update_pkg]
- name: Installing LAMP Stack
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "httpd"
    - "php"
    - "php-common"
    - "php-mysql"
    - "php-gd"
    - "php-xml"
    - "php-mbstring"
  notify: Restart Apache
  tags: [installpkg]
- name: Install mariadb
  yum:
          name: "{{ item }}"
          state: latest
  loop:
          - " mariadb-server "
          - " mariadb " 
  notify: Restart MariaDB
  tags: [install_mariadb]
# MySQL Configuration
- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  tags: [mariadb_rootpass]
- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  loop:
    - " ::1 "
    - " 127.0.0.1 "
  tags: [mariadb_rootpass]
- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
  tags: [remove_testdb]

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
  tags: [remove_usertest]
- name: Create the users
- name: Create user defined databases
  mysql_db:
    name: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  loop: 
    - "{{ mariadb_databases }}"
  register: db_creation
  tags: mariadb