---
- name: set hostname
  shell: hostnamectl set-hostname "{{server.yourdomain.com}}"
  tags: [set_hostname]

- name: Add epel-repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  tags: [enable_epel]

- name: disable php5 repository
  yum_repository:
    name: remi-php54
    enabled: no
  tags: [disable-php54]

- name: enable php73 repository
  yum_repository:
    name: remi-php73
    enabled: no
  tags: [enable-php73]

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: [mariadb]

- name: update packages
  yum:
      name: "*"
      state: present
  tags: [update_pkg]
- name: Installing LAMP Stack
  yum:
    name: {{ whit_items }}
    state: present
  loop:
    - "httpd"
    - "php"
    - "php-common"
    - "php-mysql"
    - "php-gd"
    - "php-xml"
    - "php-mbstring"
    - "php-mcrypt"
  notify: Restart Apache
  tags: [installpkg]
- name: Install mariadb
  yum:
          name: "{{ item }}"
          state: latest
  loop:
          - " mariadb-server "
          - " mariadb " 
  notify: Restart MariaDB
  tags: [install_mariadb]
# MySQL Configuration
- name: Update MySQL root password for all root accounts
  mysql_user: 
    name: root 
    host: {{ item }} 
    password: {{ mysql_root_password }}
    login_user: root
    login_password: ""
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: [set_root_pass]
